// Client-side loader for articles.json (generated by update_fetcher.py server-side)
async function loadFeed(){
  try{
    const r = await fetch('public/articles.json', {cache: 'no-store'});
    if(!r.ok) throw new Error('articles.json not found');
    const articles = await r.json();
    const feed = document.getElementById('main-feed');
    feed.innerHTML = '';
    for(const a of articles){
      const el = document.createElement('article');
      el.className = 'card';
      const imgSrc = a.image_local || a.image || '';
      const imgHtml = imgSrc ? `<div class="thumb"><img src="${imgSrc}" alt=""></div>` : '';
      el.innerHTML = `
        ${imgHtml}
        <div class="content">
          <h2><a href="${a.link}" target="_blank" rel="noopener">${a.title}</a></h2>
          <p class="meta">${a.source} • ${a.date}</p>
          <p class="summary">${a.summary}</p>
        </div>
      `;
      feed.appendChild(el);
    }
  }catch(err){
    document.getElementById('main-feed').innerHTML = '<p style="padding:20px">Could not load articles yet — run the workflow to generate public/articles.json.</p>';
    console.warn(err);
  }
}
loadFeed();
